print("Welcome to the print calculator")
print("Enter the bill")
bill = input()
print("Enter the tip percentage")
tip = input()
print("Enter the number of people")
people = input()
per_person_tip = ((float(bill)*float(tip))/100)/float(people)
total_bill = float(bill) + float(per_person_tip)
bill_per_person = total_bill/float(people)
print(f"Per person bill is {bill_per_person:.2f}")